### PR TITLE
Relationship type and measurement type update create

### PR DESCRIPTION
**Pull request by dafuga**
Added measurement type and relationship type persistance support.

### CODE REVIEW

**Comment by sheldond** [comment]
Thanks! After finishing #5 then this PR should be good to go.

**Comment by dafuga** [comment]
@sheldond I fixed all the issues and also closed the other PR as this one encompasses everything!

**Comment by sheldond** [comment]
@dafuga thanks, just one issue remains which is the `is_entity?` method, let's try to get rid of that method completely, I think you can replace lines 22 and 40 with something like this:
```
response_hash.has_key(name)? ? (new response_hash[name]) : (new response_hash)
```
Would that work?

Once that's done please update the `version.rb` file and then we can also publish a new version to use in Nebo!

**Comment by dafuga** [comment]
Hey @sheldond thanks, I already made the change, but I am actually adding subscription and system on the gem right now, perhaps it is better for you to publish the gem once those changes are made?

**Comment by sheldond** [comment]
Yes sounds good! Thanks!

**Pull request closed without merging**
